name: baseproject
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

################################################  UI库  ###################################################
  city_pickers: 1.1.3         # 城市选择器
  intro_slider: 4.2.0         # 启动时的滑动引导页
  intro_views_flutter: 3.2.0  # 有动画效果的引导页
  smooth_star_rating: 1.1.1   # 可滑动的评分组件
  timelines: 0.1.0            # 时间轴
  timeline_tile: 2.0.0        # 时间轴
  fl_chart: 0.55.2            # 饼图、条形图等
  flutter_echarts: 2.4.0      # 饼图、条形图等
  badges: 2.0.3               # 红点角标
  table_calendar: 3.0.8       # 日历
  unicorndial: 1.1.5          # 旋转弹出菜单
  flutter_speed_dial: 6.2.0   # 旋转弹出菜单
  full_screen_menu: 1.0.0     # 全屏弹出菜单
  flutter_slidable: 2.0.0     # 侧滑菜单
  flutter_swipe_action_cell: 3.0.4  # 侧滑菜单
  argon_buttons_flutter: 1.1.0      # 按钮变换动画
  shimmer: 2.0.0              # 从左到右跑马灯闪烁字体
  sleek_circular_slider: 2.0.1      # 各种样式的进度环
  syncfusion_flutter_sliders: 20.3.59 # 拖动进度条
  flutter_easyloading: 3.0.5  # 弹窗
  flutter_screenutil: 5.6.0   # 屏幕适配工具

  azlistview: 2.0.0           # 城市列表、联系人列表的索引悬停
  flutter_staggered_grid_view: 0.6.2  # 多样式组合列表
  flutter_staggered_animations: 1.1.1 # 多样式组合列表的动画
  pull_to_refresh: 2.0.0      # 下拉刷新，上拉加载
  flutter_reorderable_list: 1.2.0     # 可拖动的列表
  reorderables: 0.5.1         # 可拖动的列表，网格



################################################  功能库  ###################################################
  provider: 6.0.4             # 状态管理
  dio: 4.0.6                  # 网络库
  retrofit: 3.3.1             # 网络库
  webview_flutter: 3.0.4      # webview
  permission_handler: 10.2.0  # 权限库

  shared_preferences: 2.0.15  # sp存储
  sqflite: 2.2.0+3            # 数据库
  path_provider: 2.0.11       # 适配多平台查找可用文件系统路径
  file_picker: 5.2.2          # 打开文件系统

  url_launcher: 6.1.7         # 吊起系统应用
  amap_flutter_map: 3.0.0     # 高德地图
  amap_flutter_location: 3.0.0  # 高德定位
  jpush_flutter: 2.4.0        # 极光推送
  jmessage_flutter: 2.2.0     # 极光IM

################################################  多媒体库  ###################################################
  video_player: 2.4.8         # 视频播放器
  flick_video_player: 0.5.0   # 视频播放器
  better_player: 0.0.83       # 视频播放器
  chewie: 1.3.6               # 视频播放器
  youtube_player_flutter: 8.1.1 # 视频播放器
  audioplayers: 1.1.1         # 音频播放器
  assets_audio_player: 3.0.6  # 音频播放器
  flutter_sound: 9.2.13       # 音频录制
  photo_view: 0.14.0          # 大图预览，可放大缩小
  image_picker: 0.8.6         # 图片选择器
  wechat_assets_picker: 8.1.4 # 基于微信UI的图片选择器
  image_cropper: 3.0.1        # 图片裁剪
  wechat_camera_picker: 3.6.3 # 基于微信UI的相机
  gallery_saver: 2.3.2        # 图片、视频保存


################################################  第三方库  ###################################################
  flutter_signin_button: 2.0.0     # 社交帐号登录





dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

